apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: photoatom
servers: 1
agents: 3
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6445"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer

  - port: 443:443
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
    nodeLabels:
      - label: worker=photoatom-0
        nodeFilters:
          - agent:0
      - label: worker=photoatom-1
        nodeFilters:
          - agent:1
      - label: worker=photoatom-2
        nodeFilters:
          - agent:2
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    labels:
      - label: worker=photoatom-0
        nodeFilters:
          - agent:0
      - label: worker=photoatom-1
        nodeFilters:
          - agent:1
      - label: worker=photoatom-2
        nodeFilters:
          - agent:2
